clc;
clear;
close all;
wc1=0.25*pi;
wc2=0.75*pi;
N = input('Enter the value of N=');
alpha = (N-1)/2;
eps = 0.001;
n = 0:1:N-1;
hd = (sin(wc1*(n-alpha+eps))-sin(wc2*(n-alpha+eps)))./(pi*(n-alpha+eps));
wr = boxcar(N);
wh=hamming(N);
wn=hanning(N);
wt=bartlett(N);
hn = hd.*wr';
hn1=hd.*wh';
hn2=hd.*wn';
hn3=hd.*wt';
w = 0:0.01:pi;
h = freqz(hn,1,w);
h1 = freqz(hn1,1,w);
h2 = freqz(hn2,1,w);
h3=freqz(hn3,1,w);
figure;
subplot(2,3,1);
plot(w/pi,10*log10(abs(h)));
title('Low pass filter using rectangular window');
xlabel('Normalized frequency');
ylabel('Magnitude in dB');
subplot(2,3,2);
plot(w/pi,10*log10(abs(h1)));
title('low pass filter using hamming window');
xlabel('Normalized frequency');
ylabel('Magnitude in dB');
subplot(2,3,3);
plot(w/pi,10*log10(abs(h2)));
title('low pass filter using hanning window');
xlabel('Normalized frequency');
ylabel('Magnitude in dB');
subplot(2,3,4);
plot(w/pi,10*log10(abs(h3)));
title('low pass filter using bartlett window');
xlabel('Normalized frequency');
ylabel('Magnitude in dB');
subplot(2,3,5);
title('Triangular window Sequence');
xlabel('No. of Samples');
ylabel('Amplitude');
stem(wt)